apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sigma-backend-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/subnets: subnet-0811da083016b2867,subnet-0a140ec48b1d178a8
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:048271428028:certificate/92cb9944-e744-409d-932e-b0218a4c026b
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
    - host: www.3-sigma-server.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sigma-backend-service
                port:
                  number: 80
